# Use root/example as user/password credentials
version: '3.1'

services:

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: go_simple_framework
    depends_on:
      - db
    ports:
      - 8000:8000


  db:
    image: mysql
    container_name: godockerDB
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080